### ISSUE TITLE
Paper reference

### ISSUE THREAD

**Issue by lchunleo** [deepwilson/JPEG-artifacts-removal-using-DnCNN#1]
Hi
 Thanks for sharing your code. May i know which paper is the code based on? thank you

**Comment by deepwilson** [comment]
@lchunleo Thanks for going through the code. 

The paper referred to is [Beyond a Gaussian Denoiser: Residual Learning of Deep CNN for Image Denoising](http://www4.comp.polyu.edu.hk/~cslzhang/paper/DnCNN.pdf)
